# Generated by Django 3.2.14 on 2022-08-03 14:02

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('menu_time', models.TextField()),
                ('Status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Approved')], default=0)),
            ],
        ),
    ]
