# Generated by Django 3.2.14 on 2022-08-04 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twos', '0003_auto_20220803_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='menu_made',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
