# Generated by Django 3.2.14 on 2022-08-04 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twos', '0005_menu_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-reservation_made']},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-feedback_made']},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['-menu_made']},
        ),
    ]
