# Generated by Django 3.2.14 on 2022-08-07 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twos', '0007_signup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='menu',
        ),
    ]
