# Generated by Django 3.2.14 on 2022-08-07 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twos', '0009_auto_20220807_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(),
        ),
    ]
