# Generated by Django 3.2.16 on 2022-11-16 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twos', '0010_alter_booking_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='first_name',
            field=models.TextField(max_length=20),
        ),
    ]
